### ISSUE TITLE
Error Eval webpack

### ISSUE THREAD

**Issue by YOUDYPARRA** [noovil/chrome-extension-manifestv3#1]
hi, i use this but i have error: devtool: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". .. and i do this -> [https://stackoverflow.com/questions/48047150/chrome-extension-compiled-by-webpack-throws-unsafe-eval-error](url), another idea? best gard thanks for read,

**Comment by noovil** [comment]
Hey, the link is not working. Maybe you'd like to show me a minimal working code?

**Comment by YOUDYPARRA** [comment]
hi again
https://stackoverflow.com/questions/48047150/chrome-extension-compiled-by-webpack-throws-unsafe-eval-error
![eval error](https://user-images.githubusercontent.com/12281669/150366218-685b7d5a-4bc3-4dbe-8a48-18b78414536a.jpg)

and my code whitout node modules directory. please add in your test
[https://github.com/YOUDYPARRA/firebase-chrome-extension.git](url)
https://github.com/YOUDYPARRA/firebase-chrome-extension.git

**Comment by noovil** [comment]
Try changing your mode to production in webpack.config.js

**Comment by pranvendra** [comment]
This works for me
